// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FilePickerController from "./file_picker_controller"
application.register("file-picker", FilePickerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import NotificationController from "./notification_controller"
application.register("notification", NotificationController)

import UploadedFileController from "./uploaded_file_controller"
application.register("uploaded-file", UploadedFileController)
